### ISSUE TITLE
Problem when I try to run create invoice

### ISSUE THREAD

**Issue by penmanro** [necenzurat/smartbill#1]
Error
Call to undefined method Necenzurat\SmartBill\SmartBillFacade::createInvoice()

[2021-03-17 04:42:57] production.ERROR: Call to undefined method Necenzurat\SmartBill\SmartBillFacade::createInvoice() {"userId":50,"exception":"[object] (Error(code: 0): Call to undefined method Necenzurat\\SmartBill\\SmartBillFacade::createInvoice() at D:\\Program Files\\VertrigoServ\\www\\app\\Http\\Controllers\\CheckoutController.php:243)
[stacktrace]
#0 [internal function]: App\\Http\\Controllers\\CheckoutController->processWalletPayment(Object(Illuminate\\Http\\Request))

PHP 7.3.27
Laravel Framework 7.28.3

**Comment by necenzurat** [comment]
not sure... any other details?

**Comment by alinrzv** [comment]
@necenzurat , facades is served as static  , use static call
  $output = SmartBill::createInvoice($invoice);
     instead of 
 $smartbill = new SmartBill;
 $output = $smartbill->createInvoice($invoice); 

Change the usage demo , static call works , tested , you have a typo in the usage example as well , don't know if that is related , $smarrtbill->createInvoice($invoice) , notice the $smarrtbill  !  instead $smartbill , you can make some tests with setup:
PHP 7.3.27 Laravel Framework 7.28.3 and make the related updates if any or change the usage example !

**Comment by necenzurat** [comment]
Sorry for the late reply
@penmanro add it manually to config/app.php  or have you disabled laravel providers autoloading?
@alinrzv i just used their class class and made it suits my needs.
