### ISSUE TITLE
Laravel 9 & PHP 8.1

### ISSUE THREAD

**Issue by claumaries** [necenzurat/smartbill#2]
I'm trying to integrate the package with Laravel 9 (the latest release) and PHP 8.1 but it's not compatible. Any plans to make the package compatible with Laravel 9 and PHP 8.1?

**Comment by AhsanShabbir** [comment]
@claumaries 

#3  should fix this. Please wait for the original developer to merge this request.
Otherwise, if you need a quick solution then just run the following

`composer require ahsanshabbir/smartbill:1.1.0`

Good luck

**Comment by claumaries** [comment]
@AhsanShabbir cheers! I'll give it a try

**Comment by necenzurat** [comment]
fixed
